// Generated by update_market.py — do not edit by hand.
const MARKET = {
  "updated": "2026-08-25",
  "inventorySource": "Realtor.com via FRED, series ACTLISCOU15007 (monthly)",
  "inventory": [
    {
      "month": "2024-08",
      "count": 306
    },
    {
      "month": "2024-09",
      "count": 302
    },
    {
      "month": "2024-10",
      "count": 305
    },
    {
      "month": "2024-11",
      "count": 318
    },
    {
      "month": "2024-12",
      "count": 346
    },
    {
      "month": "2025-01",
      "count": 352
    },
    {
      "month": "2025-02",
      "count": 361
    },
    {
      "month": "2025-03",
      "count": 368
    },
    {
      "month": "2025-04",
      "count": 398
    },
    {
      "month": "2025-05",
      "count": 401
    },
    {
      "month": "2025-06",
      "count": 389
    },
    {
      "month": "2025-07",
      "count": 366
    },
    {
      "month": "2025-08",
      "count": 360
    },
    {
      "month": "2025-09",
      "count": 356
    },
    {
      "month": "2025-10",
      "count": 338
    },
    {
      "month": "2025-11",
      "count": 341
    },
    {
      "month": "2025-12",
      "count": 356
    },
    {
      "month": "2026-01",
      "count": 342
    },
    {
      "month": "2026-02",
      "count": 346
    },
    {
      "month": "2026-03",
      "count": 346
    },
    {
      "month": "2026-04",
      "count": 354
    },
    {
      "month": "2026-05",
      "count": 369
    },
    {
      "month": "2026-06",
      "count": 406
    },
    {
      "month": "2026-07",
      "count": 418
    }
  ],
  "years": {
    "2023": {
      "sf": {
        "sales": 286,
        "volume": 467000000,
        "median": 1137500
      },
      "condo": {
        "sales": 294,
        "volume": 291400000,
        "median": 722500
      },
      "land": {
        "sales": 110,
        "volume": 134000000,
        "median": null
      },
      "note": "Full year. Medians per Hawaii Realtors statewide statistics (HIS/Kauai Board data); volumes per HIS-based recap. Island total \u2248 690 sales / \u2248 $892M."
    },
    "2024": {
      "sf": {
        "sales": 358,
        "volume": 742200000,
        "median": 1368750
      },
      "condo": {
        "sales": 290,
        "volume": 280400000,
        "median": 775500
      },
      "land": {
        "sales": 119,
        "volume": 157500000,
        "median": null
      },
      "note": "Full year, MLS-based recap. Island total \u2248 767 sales / \u2248 $1.18B."
    },
    "2025": {
      "sf": {
        "sales": 423,
        "volume": 825110185,
        "median": 1200000
      },
      "condo": {
        "sales": 276,
        "volume": 275276124,
        "median": 815000
      },
      "land": {
        "sales": 92,
        "volume": 190028425,
        "median": 950000
      },
      "note": "Full year, Hawaii Information Service. Island total 791 sales / $1.29B. Luxury: 83 sales above $3M reported (median $4.31M, top sale $27.6M \u2014 brokerage-reported)."
    },
    "2026 H1": {
      "sf": {
        "sales": 175,
        "volume": 364703149,
        "median": 1325000
      },
      "condo": {
        "sales": 118,
        "volume": 119318025,
        "median": 839500
      },
      "land": {
        "sales": 36,
        "volume": 53231608,
        "median": 841000
      },
      "note": "First half 2026, Hawaii Information Service (published Aug 7, 2026). Half-year volume all types $537.3M. Q2 sales: 98 single-family, 64 condo, 22 land."
    }
  }
};

// Statewide pulse — Realtor.com inventory via St. Louis Fed (FRED), keyless CSV endpoints.
// Refreshed by the ops cycle when FRED publishes a new month. As of July 2026:
MARKET.statewide = {
  asof: "July 2026",
  active_total: 6711,
  counties: {
    kauai:  { active: 418,  median_list: 1550000 },
    oahu:   { active: 3506, median_list: 675000 },
    maui:   { active: 1437, median_list: 1000000 },
    hawaii: { active: 1350, median_list: 609950 }
  }
};
