// Generated by update_market.py — do not edit by hand.
const MARKET = {
  "updated": "2026-08-24",
  "inventorySource": "Realtor.com via FRED, series ACTLISCOU15007 (monthly)",
  "inventory": [
    {
      "month": "2024-08",
      "count": 306
    },
    {
      "month": "2024-09",
      "count": 302
    },
    {
      "month": "2024-10",
      "count": 305
    },
    {
      "month": "2024-11",
      "count": 318
    },
    {
      "month": "2024-12",
      "count": 346
    },
    {
      "month": "2025-01",
      "count": 352
    },
    {
      "month": "2025-02",
      "count": 361
    },
    {
      "month": "2025-03",
      "count": 368
    },
    {
      "month": "2025-04",
      "count": 398
    },
    {
      "month": "2025-05",
      "count": 401
    },
    {
      "month": "2025-06",
      "count": 389
    },
    {
      "month": "2025-07",
      "count": 366
    },
    {
      "month": "2025-08",
      "count": 360
    },
    {
      "month": "2025-09",
      "count": 356
    },
    {
      "month": "2025-10",
      "count": 338
    },
    {
      "month": "2025-11",
      "count": 341
    },
    {
      "month": "2025-12",
      "count": 356
    },
    {
      "month": "2026-01",
      "count": 342
    },
    {
      "month": "2026-02",
      "count": 346
    },
    {
      "month": "2026-03",
      "count": 346
    },
    {
      "month": "2026-04",
      "count": 354
    },
    {
      "month": "2026-05",
      "count": 369
    },
    {
      "month": "2026-06",
      "count": 406
    },
    {
      "month": "2026-07",
      "count": 418
    }
  ],
  "years": {
    "2023": {
      "sf": {
        "sales": 286,
        "volume": null,
        "median": 1138500
      },
      "condo": {
        "sales": 294,
        "volume": null,
        "median": null
      },
      "land": {
        "sales": 110,
        "volume": null,
        "median": null
      },
      "note": "Sales counts from 2024 recap comparisons; 2023 volumes not published."
    },
    "2024": {
      "sf": {
        "sales": 358,
        "volume": 742200000,
        "median": 1368750
      },
      "condo": {
        "sales": 290,
        "volume": 280400000,
        "median": null
      },
      "land": {
        "sales": 119,
        "volume": 157500000,
        "median": null
      },
      "note": "Full year, MLS-based recap. Island total \u2248 767 sales / \u2248 $1.18B."
    },
    "2025": {
      "sf": {
        "sales": 384,
        "volume": null,
        "median": 1200000
      },
      "condo": {
        "sales": null,
        "volume": null,
        "median": null
      },
      "land": {
        "sales": null,
        "volume": null,
        "median": null
      },
      "note": "Partial year: single-family figures are Jan\u2013Nov YTD; no full-year all-type recap was published. Luxury: 83 sales above $3M (median $4.31M, top sale $27.6M)."
    },
    "2026 H1": {
      "sf": {
        "sales": null,
        "volume": 364700000,
        "median": 1300000
      },
      "condo": {
        "sales": null,
        "volume": 119300000,
        "median": 905000
      },
      "land": {
        "sales": null,
        "volume": 53200000,
        "median": 948500
      },
      "note": "First half 2026. Medians are Q2 2026. Half-year volume all types \u2248 $537M. Q2 sales: 98 single-family, 64 condo, 22 land."
    }
  }
};
