#!/usr/bin/env python3
"""Moku — market data updater.

Fetches the latest Kauai County active-listings series from FRED (Realtor.com data)
and rewrites market-data.js. The yearly sales figures are sourced manually from
published market reports (sources in market.html) and live here until the MLS
feed automates them. Run:  python3 update_market.py
"""
import json
import subprocess
from datetime import date
from pathlib import Path

FRED_CSV = "https://fred.stlouisfed.org/graph/fredgraph.csv?id=ACTLISCOU15007"

# Sourced from published market reports — see the Sources section of market.html.
# "~" marks values summed from district tables (rough); None = not published.
YEARS = {
    "2023": {
        "sf":    {"sales": 286, "volume": None, "median": 1138500},
        "condo": {"sales": 294, "volume": None, "median": None},
        "land":  {"sales": 110, "volume": None, "median": None},
        "note":  "Sales counts from 2024 recap comparisons; 2023 volumes not published.",
    },
    "2024": {
        "sf":    {"sales": 358, "volume": 742200000, "median": 1368750},
        "condo": {"sales": 290, "volume": 280400000, "median": None},
        "land":  {"sales": 119, "volume": 157500000, "median": None},
        "note":  "Full year, MLS-based recap. Island total ≈ 767 sales / ≈ $1.18B.",
    },
    "2025": {
        "sf":    {"sales": 384, "volume": None, "median": 1200000},
        "condo": {"sales": None, "volume": None, "median": None},
        "land":  {"sales": None, "volume": None, "median": None},
        "note":  "Partial year: single-family figures are Jan–Nov YTD; no full-year all-type recap was published. Luxury: 83 sales above $3M (median $4.31M, top sale $27.6M).",
    },
    "2026 H1": {
        "sf":    {"sales": None, "volume": 364700000, "median": 1300000},
        "condo": {"sales": None, "volume": 119300000, "median": 905000},
        "land":  {"sales": None, "volume": 53200000, "median": 948500},
        "note":  "First half 2026. Medians are Q2 2026. Half-year volume all types ≈ $537M. Q2 sales: 98 single-family, 64 condo, 22 land.",
    },
}


def fetch_inventory():
    csv = subprocess.run(["curl", "-s", "--max-time", "30", FRED_CSV],
                         capture_output=True, text=True, check=True).stdout
    rows = csv.strip().splitlines()[1:]
    series = []
    for row in rows[-24:]:
        d, v = row.split(",")
        if v.strip() in ("", "."):
            continue
        series.append({"month": d[:7], "count": int(float(v))})
    return series


def main():
    inventory = fetch_inventory()
    out = {
        "updated": date.today().isoformat(),
        "inventorySource": "Realtor.com via FRED, series ACTLISCOU15007 (monthly)",
        "inventory": inventory,
        "years": YEARS,
    }
    target = Path(__file__).parent / "market-data.js"
    target.write_text(
        "// Generated by update_market.py — do not edit by hand.\n"
        "const MARKET = " + json.dumps(out, indent=2) + ";\n"
    )
    print(f"Wrote {target} — inventory through {inventory[-1]['month']} "
          f"({inventory[-1]['count']} active listings)")


if __name__ == "__main__":
    main()
